version: "3"
services:
  app:
    container_name: golang-container
    build: .
    depends_on:
      - db
    # links:
    #   - db # see https://docs.docker.com/compose/networking/ so access db at mysql://db:3306
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: demodb
      DB_USERNAME: test
      DB_PASSWORD: test

  db:
    # build:
    #   context: .
    #   dockerfile: Dockerfile-mysql
    image: mysql:5.7.22
    container_name: db-mysql-container
    # command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql #This will import the dump (init.sql file) on container start creating the database and table
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root #password
      MYSQL_DATABASE: demodb
      MYSQL_USER: test
      MYSQL_PASSWORD: test
